In [1]:
import lasio

In [2]:
import lasio.examples
las = lasio.examples.open("1001178549.las")
#We can use lasio.read() to open any file file or URL.

In [3]:
las.version
#The lasio.read() function returns a lasio.LASFile object. Each of the standard LAS sections can be accessed as an attribute

[HeaderItem(mnemonic="VERS", unit="", value="2.0", descr="CWLS Log ASCII Stan...),
 HeaderItem(mnemonic="WRAP", unit="", value="YES", descr="Multiple lines per ...)]

In [4]:
lasio.SectionItems
#Each LAS section is represented as a lasio.SectionItems object. The others, for LAS 2.0 files, are present as las.well, las.curves, and las.params

lasio.las_items.SectionItems

In [5]:
print(las.curves)
#We can print the sections as easy to read tables

Mnemonic  Unit    Value         Description                                   
--------  ----    -----         -----------                                   
DEPT      FT      0   1  0  0   1 DEPTH                                       
GSGR      API     31 310  0  0  2 GAMMA RAY                                   
GSTK      API     31 797  0  0  3 ????????                                    
GST       API     99 999 99  0  4 ????????                                    
GSK       PERCNT  31 721  1  0  5 ????????                                    
GSTH      PPM     31 790  0  0  6 THORIUM                                     
GSUR      PPM     31 792  0  0  7 URANIUM                                     
NCNPL     PERCNT  42 890  1  0  8 NEUTRON POROSITY (LIMESTONE)                
DLDPL     PERCNT  43 890 10  0  9 DENSITY POROSITY (LIMESTONE)                
DLDC      GM/CC   43 356  0  0  10 DENSITY CORRECTION                         
DLPE      B/E     43 358  0  0  11 PHOTO-ELECTRIC EF

In [6]:
las.data.shape

(5, 27)

In [7]:
las.data 
#The data is present as a numpy.ndarray at las.data

array([[1.7835000e+03,           nan,           nan,           nan,
                  nan,           nan,           nan,           nan,
                  nan,           nan,           nan,           nan,
                  nan,           nan, 5.0646500e+01, 8.3871000e+00,
        8.4396000e+00, 5.5100000e+01, 5.6900000e-02, 5.6000000e+02,
        1.7500000e+02, 5.0000000e-02, 4.5330000e-01, 1.8930420e+03,
        9.2605000e+01,           nan,           nan],
       [1.7837500e+03,           nan,           nan,           nan,
                  nan,           nan,           nan,           nan,
                  nan,           nan,           nan,           nan,
                  nan,           nan, 4.9676700e+01, 8.3951000e+00,
        8.4460000e+00, 5.4355500e+01, 5.9000000e-02, 5.6000000e+02,
        1.7500000e+02, 5.0000000e-02, 4.5340000e-01, 1.8523320e+03,
        9.2778000e+01,           nan,           nan],
       [1.7840000e+03,           nan,           nan,           nan,
        

In [8]:
for curve in las.curves:
    print(curve.mnemonic + ": " + str(curve.data))
    
#We can even iterate over the curves

DEPT: [1783.5  1783.75 1784.   1784.25 1784.5 ]
GSGR: [nan nan nan nan nan]
GSTK: [nan nan nan nan nan]
GST: [nan nan nan nan nan]
GSK: [nan nan nan nan nan]
GSTH: [nan nan nan nan nan]
GSUR: [nan nan nan nan nan]
NCNPL: [nan nan nan nan nan]
DLDPL: [nan nan nan nan nan]
DLDC: [nan nan nan nan nan]
DLPE: [nan nan nan nan nan]
DLDN: [nan nan nan nan nan]
DLCL: [nan nan nan nan nan]
DLTN: [nan nan nan nan nan]
IDGR: [50.6465 49.6767 48.6313 47.7717 48.1149]
ACCL1: [8.3871 8.3951 8.4052 8.4173 8.4253]
ACCL2: [8.4396 8.446  8.446  8.4438 8.446 ]
ACTC: [55.1    54.3555 54.4444 55.3111 56.3222]
ACAPL: [0.0569 0.059  0.0581 0.0577 0.0585]
IDIM: [560. 560. 560. 560. 560.]
IDID: [175. 175. 175. 175. 175.]
IDIDC: [0.05 0.05 0.05 0.05 0.05]
IDL3: [0.4533 0.4534 0.4537 0.4538 0.4539]
IDTN: [1893.042  1852.332  1831.9766 1831.9766 1811.6211]
IDSP: [92.605  92.778  92.9482 93.1103 93.2671]
MEL1: [nan nan nan nan nan]
ME: [nan nan nan nan nan]


In [9]:
las.index
#The first curve in the LAS file – usually the depth – is present as las.index

array([1783.5 , 1783.75, 1784.  , 1784.25, 1784.5 ])

In [10]:
las["IDTN"]
#Curves are also accessible from the LASFile object as items.

array([1893.042 , 1852.332 , 1831.9766, 1831.9766, 1811.6211])

In [11]:
las1 = lasio.examples.open('6038187_v1.2.las')
df=las1.df()
#he lasio.LASFile.df() method converts the LAS data to a pandas.DataFrame.

In [12]:
df.head(10)

CALI   DFAR  DNEAR     GAMN  NEUT       PR     SP     COND
DEPT                                                              
0.05  49.765  4.587  3.382      NaN   NaN      NaN    NaN      NaN
0.10  49.765  4.587  3.382 -2324.28   NaN  115.508 -3.049 -116.998
0.15  49.765  4.587  3.382 -2324.28   NaN  115.508 -3.049 -116.998
0.20  49.765  4.587  3.382 -2324.28   NaN  115.508 -3.049 -116.998
0.25  49.765  4.587  3.382 -2324.28   NaN  115.508 -3.049 -116.998
0.30  49.765  4.587  3.382 -2324.28   NaN  115.508 -3.049 -116.998
0.35  49.765  4.587  3.382 -2324.28   NaN  115.508 -3.049 -116.998
0.40  49.765  4.587  3.382 -2324.28   NaN  115.508 -3.049 -116.998
0.45  49.765  4.587  3.382 -2324.28   NaN  115.508 -3.049 -116.998
0.50  49.765  4.587  3.382 -2324.28   NaN  115.508 -3.049 -116.998

In [13]:
df.tail(100)

CALI   DFAR  DNEAR     GAMN     NEUT       PR       SP     COND
DEPT                                                                      
131.65  101.576  1.425  1.270  13.9460  131.000  2671.28  102.655  965.445
131.70  101.570  1.466  1.246  23.2430  145.000  2669.91  102.652  970.385
131.75  101.588  1.461  1.280  27.8920  141.000  2665.29  102.667  965.939
131.80  101.576  1.474  1.292  20.9211  119.007  2677.46  102.588  927.913
131.85  101.576  1.489  1.289  18.5947  110.003  2663.75  102.673  894.319
...         ...    ...    ...      ...      ...      ...      ...      ...
136.40   48.604    NaN    NaN      NaN      NaN      NaN      NaN      NaN
136.45   48.555    NaN    NaN      NaN      NaN      NaN      NaN      NaN
136.50   48.555    NaN    NaN      NaN      NaN      NaN      NaN      NaN
136.55   48.438    NaN    NaN      NaN      NaN      NaN      NaN      NaN
136.60  -56.275    NaN    NaN      NaN      NaN      NaN      NaN      NaN

[100 rows x 8 columns]

In [16]:
df.describe()

CALI         DFAR        DNEAR         GAMN         NEUT  \
count  2732.000000  2701.000000  2701.000000  2691.000000  2492.000000   
mean     97.432002     1.767922     1.729209  -102.330033   441.600013   
std      13.939547     0.480333     0.372412   630.106420   370.138208   
min     -56.275000     0.725000     0.657001 -2324.280000    81.001800   
25%     101.077500     1.526000     1.535000    55.783000   158.002000   
50%     101.426000     1.758000     1.785000    74.376900   256.501500   
75%     101.582000     1.993000     1.948000    88.326900   680.500250   
max     103.380000     5.989000     3.382000   169.672000  1665.990000   

                 PR           SP         COND  
count   2692.000000  2692.000000  2697.000000  
mean   17940.522307    90.393464   478.670791  
std    22089.297212    26.725547   753.869866  
min      115.508000    -3.049000  -116.998000  
25%     2652.470000    93.495500   200.981000  
50%     2709.345000    99.994000   266.435000  
75%    50499.900000   100.623000   505.530000  
max    50499.900000   102.902000  4978.160000